# Selene linter configuration
# https://kampfkarren.github.io/selene/

std = "roblox"

[rules]
empty_if = "warn"
empty_loop = "warn"
if_same_then_else = "warn"
multiple_statements = "warn"
parenthese_conditions = "warn"
unbalanced_assignments = "warn"
